apiVersion: v1
kind: ConfigMap
metadata:
  name: Myconf-postgresql
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-service 
type: Opaque
data:
  <THE KEY FROM Secret WHICH has THE ENCODED PASSWORD>: <OUTPUT OF `echo -n 'the password' | base64`>